### ISSUE TITLE
Fails to run `npm run build`

### ISSUE THREAD

**Issue by chrisgrieser** [nathanlesage/cheatsheet-generator#5]
Using v22.8.0, After running `npm install`:

```
$ npm run build
> shortcut-generator@0.2.0 build
> webpack && node ./scripts/build.js

node:internal/crypto/hash:79
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/Users/chrisgrieser/Developer/cheatsheet-generator/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/chrisgrieser/Developer/cheatsheet-generator/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/chrisgrieser/Developer/cheatsheet-generator/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/chrisgrieser/Developer/cheatsheet-generator/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/chrisgrieser/Developer/cheatsheet-generator/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/chrisgrieser/Developer/cheatsheet-generator/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/chrisgrieser/Developer/cheatsheet-generator/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/chrisgrieser/Developer/cheatsheet-generator/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/chrisgrieser/Developer/cheatsheet-generator/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/chrisgrieser/Developer/cheatsheet-generator/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/chrisgrieser/Developer/cheatsheet-generator/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v22.8.0
```

**Comment by nathanlesage** [comment]
This looks as if a simple webpack upgrade may suffice. I can try to get this going next week, but feel free to open a PR before that.

**Comment by nathanlesage** [comment]
![image](https://github.com/user-attachments/assets/6f6542cc-6e22-4535-bc1e-27e47d1fad15)

Yup, it was *really* outdated.

I'm going to add a patch soon after verifying that everything still works and close the issue.

**Comment by nathanlesage** [comment]
Fixed, works again (with Node 20, but since I updated to the most recent version of the dependencies I'm positive Node 22 will also work).

**Comment by chrisgrieser** [comment]
thank you!
